# fly.toml app configuration file generated for thingtracker on 2023-08-12T23:14:14-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "thingtracker"
primary_region = "iad"

[build.args]
  IRON_SESSION_COMPLEX_PASSWORD='********'
  DATABASE_URL='mysql://********:********@aws.connect.psdb.cloud/hobby?ssl={"rejectUnauthorized":true}'
  FLY_REGION='iad'
  PRIMARY_REGION='iad'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
